import {createClient} from '@supabase/supabase-js'; import './style.css';
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY); const root=document.querySelector('#root'); let session=null,view='today',content=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await sb.auth.getSession();session=r.data.session;if(session){let d=await sb.from('daily_content').select('*').eq('content_date',new Date().toISOString().slice(0,10)).maybeSingle();content=d.data}render()}
function auth(){root.innerHTML=`<main class="auth"><div class="leaf">❧</div><h1>Folow Him</h1><p>A gentle place to pray, reflect, and remember His faithfulness.</p><section class="card"><form id="a"><label>Email<input id="e" type="email" required></label><label>Password<input id="p" type="password" minlength="8" required></label><button>Sign in</button><button type="button" id="new">Create account</button><button type="button" class="link" id="reset">Forgot password?</button><small id="m"></small></form></section></main>`;document.querySelector('#a').onsubmit=async x=>{x.preventDefault();let r=await sb.auth.signInWithPassword({email:e.value,password:p.value});m.textContent=r.error?.message||''};new.onclick=async()=>{let r=await sb.auth.signUp({email:e.value,password:p.value});m.textContent=r.error?.message||'Check your email to confirm your account.'};reset.onclick=async()=>{let r=await sb.auth.resetPasswordForEmail(e.value);m.textContent=r.error?.message||'Reset email sent.'}}
async function today(){return `<main><p class="eyebrow">TODAY</p><h2>Come away and be still.</h2><section class="scripture"><p class="eyebrow">TODAY'S SCRIPTURE</p><blockquote>${esc(content?.scripture_text||'Be still, and know that I am God.')}</blockquote><b>${esc(content?.scripture_reference||'Psalm 46:10')}</b></section><section class="card"><p class="eyebrow">PRAYER PROMPT</p><h3>${esc(content?.prayer_prompt||'What is on your heart today?')}</h3><button data-v="journal">Start journaling</button></section></main>`}
async function journal(){let r=await sb.from('journal_entries').select('*').order('entry_date',{ascending:false}).limit(20);return `<main><p class="eyebrow">JOURNAL</p><h2>Your quiet place.</h2><section class="card"><form id="j"><input id="jt" placeholder="Title"><textarea id="jb" rows="7" placeholder="Write your prayer or reflection..." required></textarea><button>Save entry</button></form></section><div>${(r.data||[]).map(x=>`<article class="entry"><small>${esc(x.entry_date)}</small><h3>${esc(x.title||'Prayer')}</h3><p>${esc(x.body)}</p></article>`).join('')}</div></main>`}
async function prayers(){let r=await sb.from('prayer_requests').select('*').order('updated_at',{ascending:false});return `<main><p class="eyebrow">MY PRAYERS</p><h2>Keep bringing it to Him.</h2><section class="card"><form id="pr"><input id="pt" placeholder="Prayer request" required><textarea id="pd" rows="4" placeholder="Details"></textarea><button>Add prayer</button></form></section><div>${(r.data||[]).map(x=>`<article class="entry"><span>${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.details||'')}</p>${x.status==='active'?`<button data-a="${x.id}">Mark answered</button>`:''}</article>`).join('')}</div></main>`}
async function render(){if(!session)return auth();let body=view==='today'?await today():view==='journal'?await journal():await prayers();root.innerHTML=`<header><strong>❧ Folow Him</strong><button id="out">Sign out</button></header>${body}<nav><button data-v="today">Today</button><button data-v="journal">Journal</button><button data-v="prayers">Prayers</button></nav>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});out.onclick=async()=>{await sb.auth.signOut();session=null;render()};j?.addEventListener('submit',async e=>{e.preventDefault();await sb.from('journal_entries').insert({user_id:session.user.id,title:jt.value,body:jb.value});render()});pr?.addEventListener('submit',async e=>{e.preventDefault();await sb.from('prayer_requests').insert({user_id:session.user.id,title:pt.value,details:pd.value});render()});document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{await sb.from('prayer_requests').update({status:'answered',answered_at:new Date().toISOString()}).eq('id',b.dataset.a);render()})}
sb.auth.onAuthStateChange((_e,s)=>{session=s;render()});load();
